version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - frontend
    depends_on:
      - frontend_db
  frontend_db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - frontend_db:/var/lib/postgresql/data
    networks:
      - frontend

networks:
  frontend:
volumes:
  frontend_db:
